# Generated by Django 2.2.1 on 2019-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='caa7fcddddfb4f0c878dd4b51b752947', max_length=32, unique=True),
        ),
    ]
