# Generated by Django 2.2.1 on 2019-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20190505_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='02d1f9b8dd1b319b7b8c0d525ffc4a3a', max_length=32, unique=True),
        ),
    ]
